version: "3"

services:
  prometheus:
    image: prom/prometheus
    command: ['--config.file=/monitoring/prometheus.yml']
    ports: ['9090:9090']
    volumes:
      - ./monitoring:/NEWS-BIG-DATA-ANALYSIS/

  blackbox:
    privileged: true
    image: prom/blackbox-exporter
    command: ['--config.file=/config/blackbox.yml']
    ports: ['9115:9115']
    volumes: ['./blackbox.yml:/config/blackbox.yml']